language: haskell

cache:
    directories:
        - $HOME/.stack

before_install:
    - openssl aes-256-cbc -K $encrypted_a3ca37296d87_key -iv $encrypted_a3ca37296d87_iv -in secrets.tar.enc -out secrets.tar -d
    - tar xvf secrets.tar
    - mkdir -p ~/.local/bin
    - export PATH=$HOME/.local/bin:$PATH
    - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
    - stack config set system-ghc --global true
    - stack install stack-run
    - export PATH=/opt/ghc/7.10.2/bin:$PATH

script:
    - stack --no-terminal --skip-ghc-check run

addons:
    apt:
        sources:
            - hvr-ghc
        packages:
            - ghc-7.10.2
