language: generic

cache:
    directories:
        - $HOME/.stack

before_install:
    - openssl aes-256-cbc -K $encrypted_a3ca37296d87_key -iv $encrypted_a3ca37296d87_iv -in secrets.tar.enc -out secrets.tar -d
    - tar xvf secrets.tar
    - mkdir -p ~/.local/bin
    - export PATH=$HOME/.local/bin:$PATH
    - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
    - stack setup

script:
    - stack build --no-terminal
    - stack exec Analytics
    - mkdir build
    - mv top-articles.json build

deploy:
    provider: s3
    access_key_id:
        - secure: "Z5abkNZB4XLTPELLHAl6I30U486Zkk8SDZoUmoVBljIioyfbMMfV+9raJKWXyc4gS6riZSXEFVtKVSA9RhL3ljyKqTSUzJb/365/uwRYOXYpguJXHIhsJsUncus5G6TITuXQCa/t0ETxruHlAPxIJJkBWopCIJNWScBMfBESIdoUcJPl2c4rDT0gQI+jndtaLrFtMxUyhrccfIgGzGf3kEYTJBqeErJiChpsKMt0ISYaYXQDzDIR0x3WrwuDlBWOkdloWf78Uff4acRjBV085EEQ+HIZzw/u3hAlrUEAkJ2isQ/VUVCl37mVYYH5jTwBDJG5cpCa02YXMkDyWpKx/qwsxbPu6jLu4gtHEpnWd76kqcF6+THBYmPiDJuYS/l8kqz3KwmPcNsM43VhEMYWvYrU7MqamyUdXN0NBENvkedym5tnRBc9hxI6+3qlsBKzdimqowkUoB4EcocND/ZWq4wyF9NdW3ChC3IvM85wJ5EvNu6iiw8TgCQXLaC5wqlwg6YQZuZAid2j3MDaVUTjvPikWLrFFRTrtpGlAfNDvh8FvsmfvqY1oCbCn4nmTRqPif9bHef21FiVbtcM7d7ZyEaoEjsoom0ayODq2v52E7jH3Le6ubv9ZDv+0uW/8W9KGj70UWLIijYgyqmMhJsVvf5PxGRpxlkdoOg7y5hJID8="
    secret_access_key:
        - secure: "uSEvBqBC6GrO5ttnm3CI7UdZIkFqv4IyHu2giv91y18wpbHBnBoyCBhnbe4ktL9w3Dh4uxzLy1sTfu9FX7SlKZlBb4d18A+PLH6uIqDFlw3M7hcdqyyuW2L0Q0iS0h2M73cK067mHMRxVAoY2j8w/ldAED4PzbLorwm7OIbfMCS4AvEpdQ6asQjj2EvElUooHIKz6W/SlOk7APP2LRKbfLAOKQIp9z7nx/mNuZmhoNJytXFVCwVQlkntD8OP4oSLZMjdJhhCpo1gc2UQrIWtwzUK6ZfhhGOfAuKsXYZ86zRceLxZSB0p87kgKHUzhna/6WWaJrmaqhtlM5U6qWcek34LJUhp1gJxGTX+W4uGwIIs/TE7FFA7a+Vwo/fygveof8txdDbCDpMBygbIfyzRJqxKSyxObj9nvBjMMGJ983Yr8tGCp7XFoDg35uPzgHcwUJ3bWuWgO5Xrxk5j1/lbZzgE2sLhAIMClVu1ejvDLuPnlSD9kItZ1YqZfq+pCVdmjIFsWiwyUWIZss3tklUy7CG/bMoZRHKivyk1p6SymFFsEtGcQdQIwmBMN9prazjW4oj1QI8Bws/BgnlqPD55duGVlI/bH808f+nCEb7J9JJi/o7sRV732U4TR6Cigtp7TG70hIEMYXuCyi/3UBRhTMTfrcam5ufoeVEc5Pds9nM="
    bucket: "data.ohlasy.info"
    region: "eu-central-1"
    skip_cleanup: true
    local_dir: build
    acl: public_read

addons:
    apt:
        packages:
            - libgmp-dev
